import { getDb, closeDb } from './connection';
import { runMigrations } from './migrate';
import { round2 } from '../utils/money';
import { addDays, today } from '../utils/dates';
import { calculateScheme } from '../services/schemeService';
import { createPurchaseOrder, receivePurchaseOrder } from '../services/procurementService';
import { recordSupplierPayment } from '../services/outstandingService';
import { logActivity } from '../services/activityService';
import type { ProductRow } from '../types';

/**
 * SEED v2 - DEMO DISTRIBUTOR NETWORK AND PROCUREMENT HISTORY
 * ==========================================================
 *
 * Generates the buying side of the pharmacy on top of the v1 trading history.
 *
 * EVERYTHING HERE IS SYNTHETIC.
 *
 * The distributors are invented. Their catalogues, prices, schemes and stock
 * figures are generated by the arithmetic in this file. Nothing is scraped
 * from, downloaded from, or connected to Retailio, Pharmarack, or any other
 * commercial platform, and no figure here represents real market data.
 *
 * Deterministic: a fixed PRNG seed means `npm run seed` reproduces the same
 * network every time, so a rehearsed demo shows the same numbers on the day.
 */

const SEED = 20260820;

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function random(): number {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(SEED);
const between = (min: number, max: number) => min + rand() * (max - min);
const intBetween = (min: number, max: number) => Math.floor(between(min, max + 1));
const pick = <T>(arr: readonly T[]): T => arr[Math.floor(rand() * arr.length)];
const chance = (p: number) => rand() < p;

/* -------------------------------------------------------------------------- */
/* Fictional distributor network                                               */
/* -------------------------------------------------------------------------- */

/**
 * All names are invented for this demonstration. Any resemblance to an actual
 * trading company is coincidental and unintended.
 */
const DISTRIBUTOR_NAMES = [
  'ABC Pharma Distributors', 'Medline Pharma Distributors', 'CarePlus Pharma',
  'PrimeMed Distributors', 'HealthBridge Pharma', 'CityMed Stockists',
  'Apex Pharma Supply', 'LifeCare Distributors', 'Sanjivani Medico',
  'Bluewave Pharma Agencies', 'Vitalis Distributors', 'Sunrise Medico Supply',
  'Trinity Pharma Traders', 'Everest Drug House', 'Nova Medico Agencies',
  'Shreeji Pharma Stockists', 'Gateway Pharma Supply', 'Orbit Healthcare Distributors',
  'Pinnacle Medico', 'Radiant Pharma Traders', 'Unity Drug Distributors',
  'Sparsh Pharma Agencies', 'Konark Medico Supply', 'Deccan Pharma Stockists',
  'Sahyadri Drug Agencies', 'Millennium Pharma Supply', 'Aarogya Distributors',
  'Crestline Pharma Traders',
];

const AREAS: { area: string; city: string; pin: string; state: string }[] = [
  { area: 'MG Road', city: 'Pune', pin: '411001', state: 'Maharashtra' },
  { area: 'Shivaji Nagar', city: 'Pune', pin: '411005', state: 'Maharashtra' },
  { area: 'Kothrud', city: 'Pune', pin: '411038', state: 'Maharashtra' },
  { area: 'Hadapsar', city: 'Pune', pin: '411028', state: 'Maharashtra' },
  { area: 'Market Yard', city: 'Pune', pin: '411037', state: 'Maharashtra' },
  { area: 'Pimpri', city: 'Pimpri-Chinchwad', pin: '411018', state: 'Maharashtra' },
  { area: 'Nashik Road', city: 'Nashik', pin: '422101', state: 'Maharashtra' },
  { area: 'Civil Lines', city: 'Nagpur', pin: '440001', state: 'Maharashtra' },
  { area: 'Andheri East', city: 'Mumbai', pin: '400069', state: 'Maharashtra' },
  { area: 'Dadar West', city: 'Mumbai', pin: '400028', state: 'Maharashtra' },
];

const FIRST_NAMES = ['Ramesh', 'Suresh', 'Anil', 'Prakash', 'Deepak', 'Nitin', 'Sunita', 'Kavita', 'Meera', 'Farida', 'Imran', 'Rohit'];
const LAST_NAMES = ['Sharma', 'Patil', 'Deshmukh', 'Kulkarni', 'Joshi', 'Shah', 'Mehta', 'Rao', 'Verma', 'Nair'];

const PAYMENT_TERMS = ['Net 15', 'Net 30', 'Net 45', 'Net 60', 'Cash on delivery'];

/** Common Indian pharma trade schemes. */
const SCHEMES: { buy: number; free: number; weight: number }[] = [
  { buy: 0, free: 0, weight: 40 },
  { buy: 10, free: 1, weight: 22 },
  { buy: 20, free: 2, weight: 12 },
  { buy: 5, free: 1, weight: 8 },
  { buy: 10, free: 2, weight: 6 },
  { buy: 12, free: 1, weight: 5 },
  { buy: 25, free: 5, weight: 4 },
  { buy: 6, free: 1, weight: 3 },
];

function pickScheme(): { buy: number; free: number } {
  const total = SCHEMES.reduce((s, x) => s + x.weight, 0);
  let roll = rand() * total;
  for (const scheme of SCHEMES) {
    roll -= scheme.weight;
    if (roll <= 0) return { buy: scheme.buy, free: scheme.free };
  }
  return { buy: 0, free: 0 };
}

/** Synthetic GSTIN-shaped string. Format only — not a valid registration. */
function demoGstin(): string {
  const letters = 'ABCDEFGHIJKLMNPQRSTUVWXYZ';
  const four = Array.from({ length: 5 }, () => letters[intBetween(0, letters.length - 1)]).join('');
  return `27${four}${intBetween(1000, 9999)}${letters[intBetween(0, 25)]}1Z${intBetween(0, 9)}`;
}

function demoDrugLicense(): string {
  return `MH-${intBetween(10, 49)}-${intBetween(100000, 999999)}`;
}

/* -------------------------------------------------------------------------- */

function clearV2Data(): void {
  getDb().exec(`
    PRAGMA foreign_keys = OFF;
    DELETE FROM supplier_payments;
    DELETE FROM supplier_invoices;
    DELETE FROM purchase_receipts;
    DELETE FROM purchase_order_items;
    DELETE FROM purchase_orders;
    DELETE FROM distributor_products;
    DELETE FROM distributors;
    DELETE FROM manufacturers;
    DELETE FROM customer_payments;
    DELETE FROM purchase_return_items;
    DELETE FROM purchase_returns;
    DELETE FROM stock_adjustments;
    DELETE FROM activity_log;
    DELETE FROM sqlite_sequence WHERE name IN
      ('supplier_payments','supplier_invoices','purchase_receipts','purchase_order_items',
       'purchase_orders','distributor_products','distributors','manufacturers',
       'customer_payments','purchase_return_items','purchase_returns','stock_adjustments','activity_log');
    PRAGMA foreign_keys = ON;
  `);
}

function seedManufacturers(): void {
  const db = getDb();
  const names = (
    db
      .prepare("SELECT DISTINCT manufacturer AS name FROM products WHERE manufacturer IS NOT NULL AND manufacturer <> ''")
      .all() as { name: string }[]
  ).map((r) => r.name);

  const insert = db.prepare(
    'INSERT OR IGNORE INTO manufacturers (name, code, contact_person, phone, email) VALUES (?, ?, ?, ?, ?)',
  );

  db.transaction(() => {
    names.forEach((name, i) => {
      insert.run(
        name,
        `MFR-${String(i + 1).padStart(3, '0')}`,
        `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`,
        `+91 22 ${intBetween(20000000, 49999999)}`,
        `contact@${name.toLowerCase().replace(/[^a-z]/g, '').slice(0, 12)}-demo.test`,
      );
    });
  })();

  // Link products to their manufacturer record.
  db.exec(`
    UPDATE products
       SET manufacturer_id = (SELECT m.id FROM manufacturers m WHERE m.name = products.manufacturer)
     WHERE manufacturer IS NOT NULL
  `);
}

function seedDistributors(): number[] {
  const db = getDb();
  const suppliers = db.prepare('SELECT id FROM suppliers ORDER BY id').all() as { id: number }[];

  const insert = db.prepare(
    `INSERT INTO distributors
       (distributor_code, name, type, contact_person, phone, email, address, area, city, pin_code,
        state, gstin, drug_license_no, payment_terms, credit_days, credit_limit, delivery_days,
        min_order_value, distance_km, rating, supplier_id, status)
     VALUES (@code, @name, @type, @contact, @phone, @email, @address, @area, @city, @pin, @state,
             @gstin, @dl, @terms, @creditDays, @creditLimit, @deliveryDays, @moq, @distance,
             @rating, @supplierId, 'ACTIVE')`,
  );

  const ids: number[] = [];
  db.transaction(() => {
    DISTRIBUTOR_NAMES.forEach((name, i) => {
      const location = AREAS[i % AREAS.length];
      const terms = pick(PAYMENT_TERMS);
      const creditDays = terms === 'Cash on delivery' ? 0 : Number(terms.replace(/\D/g, '')) || 30;

      // The first eight are "local" - close, fast, and the ones the discovery
      // screen surfaces first for the default pharmacy location.
      const isLocal = i < 8;
      const type = i < 20 ? 'DISTRIBUTOR' : i < 25 ? 'STOCKIST' : 'SUPER_STOCKIST';

      ids.push(
        Number(
          insert.run({
            code: `DIST-${String(i + 1).padStart(4, '0')}`,
            name,
            type,
            contact: `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`,
            phone: `+91 ${intBetween(70000, 99999)} ${intBetween(10000, 99999)}`,
            email: `orders@${name.toLowerCase().replace(/[^a-z]/g, '').slice(0, 14)}-demo.test`,
            address: `${intBetween(1, 250)}, ${location.area}`,
            area: location.area,
            city: location.city,
            pin: location.pin,
            state: location.state,
            gstin: demoGstin(),
            dl: demoDrugLicense(),
            terms,
            creditDays,
            creditLimit: intBetween(50, 500) * 1000,
            deliveryDays: isLocal ? intBetween(0, 1) : intBetween(1, 4),
            moq: pick([0, 1000, 2000, 2500, 5000]),
            distance: isLocal ? round2(between(0.6, 8)) : round2(between(12, 180)),
            rating: round2(between(3.2, 4.9)),
            supplierId: suppliers[i % suppliers.length]?.id ?? null,
          }).lastInsertRowid,
        ),
      );
    });
  })();

  return ids;
}

/**
 * Builds each distributor's catalogue.
 *
 * Not every distributor carries every product - that is what makes supplier
 * comparison meaningful. Prices vary by a few percent around the product's PTR
 * and schemes are drawn from the weighted table, so the cheapest headline rate
 * is frequently NOT the cheapest effective cost. That tension is the whole
 * point of the comparison screen.
 */
function seedCatalogues(distributorIds: number[]): number {
  const db = getDb();
  const products = db.prepare('SELECT * FROM products').all() as (ProductRow & {
    mrp: number;
    ptr: number;
    pts: number;
  })[];

  const insert = db.prepare(
    `INSERT OR IGNORE INTO distributor_products
       (distributor_id, product_id, ptr, pts, mrp, scheme_buy_qty, scheme_free_qty,
        discount_pct, available_qty, min_order_qty, status)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'ACTIVE')`,
  );

  let count = 0;
  db.transaction(() => {
    for (const distributor of distributorIds) {
      // Each distributor carries 55-90% of the catalogue.
      const coverage = between(0.55, 0.9);
      for (const product of products) {
        if (!chance(coverage)) continue;

        // Distributors compete within a few percent of the reference PTR.
        const ptr = round2(product.ptr * between(0.93, 1.07));
        const pts = round2(ptr * between(0.88, 0.95));
        const scheme = pickScheme();
        // A discount and a free-goods scheme rarely appear together in trade.
        const discountPct = scheme.buy === 0 && chance(0.28) ? round2(between(2, 8)) : 0;

        // Availability: most lines stocked, some thin, a few out.
        const availability = rand();
        const availableQty =
          availability < 0.08 ? 0 : availability < 0.2 ? intBetween(5, 40) : intBetween(60, 900);

        insert.run(
          distributor,
          product.id,
          ptr,
          pts,
          product.mrp,
          scheme.buy,
          scheme.free,
          discountPct,
          availableQty,
          pick([1, 1, 1, 5, 10]),
        );
        count += 1;
      }
    }
  })();

  // Every product should have at least one well-stocked source, otherwise the
  // Replenishment Center recommends nothing and the demo looks broken.
  const orphaned = db
    .prepare(
      `SELECT p.id, p.ptr, p.mrp FROM products p
        WHERE NOT EXISTS (SELECT 1 FROM distributor_products dp
                           WHERE dp.product_id = p.id AND dp.available_qty > 50)`,
    )
    .all() as { id: number; ptr: number; mrp: number }[];

  db.transaction(() => {
    for (const product of orphaned) {
      const distributor = pick(distributorIds.slice(0, 8));
      const scheme = pickScheme();
      db.prepare(
        `INSERT INTO distributor_products
           (distributor_id, product_id, ptr, pts, mrp, scheme_buy_qty, scheme_free_qty,
            discount_pct, available_qty, min_order_qty, status)
         VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, 1, 'ACTIVE')
         ON CONFLICT (distributor_id, product_id) DO UPDATE SET available_qty = excluded.available_qty`,
      ).run(
        distributor,
        product.id,
        round2(product.ptr * between(0.95, 1.03)),
        round2(product.ptr * 0.92),
        product.mrp,
        scheme.buy,
        scheme.free,
        intBetween(150, 800),
      );
      count += 1;
    }
  })();

  // Point each product at its cheapest source by effective cost.
  db.exec(`
    UPDATE products SET preferred_distributor_id = (
      SELECT dp.distributor_id FROM distributor_products dp
       WHERE dp.product_id = products.id AND dp.available_qty > 0
       ORDER BY dp.ptr * (1 - dp.discount_pct / 100.0)
                / (1.0 + CAST(dp.scheme_free_qty AS REAL) / MAX(dp.scheme_buy_qty, 1))
       LIMIT 1
    )
  `);

  return count;
}

/**
 * Purchase-order history, so the procurement screens are not empty on first run.
 *
 * Orders are placed at intervals across the last 90 days and taken through the
 * real service functions - createPurchaseOrder() and receivePurchaseOrder() -
 * so the generated history exercises the actual scheme arithmetic, batch
 * creation and invoice raising rather than fabricating rows.
 */
function seedPurchaseOrders(adminId: number): { orders: number; received: number; payments: number } {
  const db = getDb();
  const distributors = db
    .prepare("SELECT id FROM distributors WHERE status = 'ACTIVE' ORDER BY distance_km LIMIT 12")
    .all() as { id: number }[];

  let orders = 0;
  let received = 0;
  let payments = 0;

  for (let dayOffset = 88; dayOffset >= 0; dayOffset -= 7) {
    const poDate = addDays(today(), -dayOffset);
    const distributor = pick(distributors);

    // Pick products this distributor actually stocks.
    const lines = db
      .prepare(
        `SELECT dp.product_id, dp.min_order_qty, dp.available_qty
         FROM distributor_products dp
         WHERE dp.distributor_id = ? AND dp.available_qty > 100
         ORDER BY RANDOM() LIMIT ?`,
      )
      .all(distributor.id, intBetween(3, 8)) as {
      product_id: number;
      min_order_qty: number;
      available_qty: number;
    }[];
    if (lines.length === 0) continue;

    try {
      const po = createPurchaseOrder({
        distributor_id: distributor.id,
        po_date: poDate,
        user_id: adminId,
        username: 'admin',
        status: 'SENT',
        items: lines.map((line) => ({
          product_id: line.product_id,
          quantity: Math.max(line.min_order_qty, intBetween(20, 120)),
        })),
      });
      orders += 1;

      // Older orders are received; the two most recent stay open so the
      // Purchase Orders screen shows work in progress.
      if (dayOffset > 14) {
        const receiptDate = addDays(poDate, intBetween(1, 4));
        receivePurchaseOrder({
          po_id: po.id,
          receipt_date: receiptDate,
          invoice_number: `INV/${poDate.slice(2, 4)}${poDate.slice(5, 7)}/${intBetween(1000, 9999)}`,
          user_id: adminId,
          username: 'admin',
          items: po.items.map((item) => ({
            po_item_id: Number(item.id),
            received_qty: Number(item.ordered_qty),
            batch_number: `PB${poDate.replace(/-/g, '').slice(2)}${intBetween(100, 999)}`,
            expiry_date: addDays(receiptDate, intBetween(400, 900)),
            manufacturing_date: addDays(receiptDate, -intBetween(30, 150)),
          })),
        });
        received += 1;
      } else if (dayOffset > 7) {
        db.prepare("UPDATE purchase_orders SET status = 'CONFIRMED' WHERE id = ?").run(po.id);
      }
    } catch {
      // A minimum-order-value rule can legitimately reject a small basket.
      // Skipping is the correct outcome, not an error to hide.
    }
  }

  // Settle roughly two thirds of the invoices raised, leaving a realistic
  // outstanding balance with some of it overdue.
  const invoices = db
    .prepare("SELECT id, distributor_id, invoice_amount FROM supplier_invoices WHERE status = 'UNPAID' ORDER BY id")
    .all() as { id: number; distributor_id: number; invoice_amount: number }[];

  for (const invoice of invoices) {
    if (!chance(0.62)) continue;
    try {
      // Some payments are partial - that is what produces a PARTIAL status.
      const amount = chance(0.75) ? invoice.invoice_amount : round2(invoice.invoice_amount * between(0.3, 0.7));
      recordSupplierPayment({
        distributor_id: invoice.distributor_id,
        invoice_id: invoice.id,
        amount,
        method: pick(['BANK', 'UPI', 'CHEQUE', 'CASH'] as const),
        user_id: adminId,
        username: 'admin',
      });
      payments += 1;
    } catch {
      /* rounding can make a full-value payment marginally exceed the balance */
    }
  }

  return { orders, received, payments };
}

/** Marks historic credit sales as unsettled so customer outstanding is non-empty. */
function seedCustomerCredit(): number {
  const db = getDb();
  // Institutional buyers are the realistic credit customers.
  const sales = db
    .prepare(
      `SELECT s.id, s.total, s.sale_date FROM sales s
       JOIN customers c ON c.id = s.customer_id
       WHERE c.customer_type = 'INSTITUTIONAL' AND s.status <> 'CANCELLED'
         AND date(s.sale_date) >= date('now', '-75 days')
       ORDER BY s.sale_date DESC LIMIT 60`,
    )
    .all() as { id: number; total: number; sale_date: string }[];

  let count = 0;
  db.transaction(() => {
    for (const sale of sales) {
      if (!chance(0.55)) continue;
      // Some fully unpaid, some part-paid.
      const paid = chance(0.4) ? round2(sale.total * between(0.2, 0.6)) : 0;
      db.prepare(
        "UPDATE sales SET payment_method = 'CREDIT', paid_amount = ?, due_date = ? WHERE id = ?",
      ).run(paid, addDays(sale.sale_date.slice(0, 10), 30), sale.id);
      count += 1;
    }
  })();
  return count;
}

/* -------------------------------------------------------------------------- */

export function seedV2(): void {
  const started = Date.now();
  const db = getDb();
  runMigrations(db);

  const admin = db.prepare("SELECT id FROM users WHERE role = 'ADMIN' LIMIT 1").get() as
    | { id: number }
    | undefined;
  const adminId = admin?.id ?? 1;

  const productCount = (db.prepare('SELECT COUNT(*) AS n FROM products').get() as { n: number }).n;
  if (productCount === 0) {
    throw new Error('No products found. Run  npm run seed  first to create the base dataset.');
  }

  console.log('  Clearing existing procurement data...');
  clearV2Data();

  console.log('  Creating manufacturer master...');
  seedManufacturers();

  console.log(`  Creating ${DISTRIBUTOR_NAMES.length} demo distributors...`);
  const distributorIds = seedDistributors();

  console.log('  Building distributor catalogues (prices, schemes, availability)...');
  const catalogueLines = seedCatalogues(distributorIds);

  console.log('  Generating purchase order history...');
  const po = seedPurchaseOrders(adminId);

  console.log('  Marking institutional credit sales...');
  const creditSales = seedCustomerCredit();

  logActivity({
    userId: adminId,
    username: 'admin',
    action: 'SEED',
    module: 'SETTINGS',
    summary: 'Generated demo distributor network and procurement history',
  });

  // Pharmacy location, used by distributor discovery.
  const settings = db.prepare('INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)');
  db.transaction(() => {
    settings.run('pharmacy_city', 'Pune');
    settings.run('pharmacy_area', 'MG Road');
    settings.run('pharmacy_pin', '411001');
    settings.run('pharmacy_state', 'Maharashtra');
  })();

  const stats = db
    .prepare(
      `SELECT (SELECT COUNT(*) FROM manufacturers)         AS manufacturers,
              (SELECT COUNT(*) FROM distributors)          AS distributors,
              (SELECT COUNT(*) FROM distributor_products)  AS catalogue,
              (SELECT COUNT(*) FROM purchase_orders)       AS pos,
              (SELECT COUNT(*) FROM supplier_invoices)     AS invoices,
              (SELECT COUNT(*) FROM supplier_payments)     AS payments,
              (SELECT COALESCE(SUM(invoice_amount - paid_amount),0) FROM supplier_invoices
                WHERE status <> 'PAID')                    AS outstanding,
              (SELECT COALESCE(SUM(total - paid_amount),0) FROM sales
                WHERE total > paid_amount)                 AS custOutstanding`,
    )
    .get() as Record<string, number>;

  console.log('');
  console.log('  Demo procurement network created');
  console.log('  ------------------------------------------------');
  console.log(`  Manufacturers          ${stats.manufacturers}`);
  console.log(`  Distributors           ${stats.distributors}`);
  console.log(`  Catalogue lines        ${stats.catalogue.toLocaleString('en-IN')} (${catalogueLines} generated)`);
  console.log(`  Purchase orders        ${stats.pos}  (${po.received} received)`);
  console.log(`  Supplier invoices      ${stats.invoices}`);
  console.log(`  Supplier payments      ${stats.payments}`);
  console.log(`  Supplier outstanding   ${round2(stats.outstanding).toLocaleString('en-IN')}`);
  console.log(`  Credit sales           ${creditSales} (customer outstanding ${round2(stats.custOutstanding).toLocaleString('en-IN')})`);
  console.log(`  Generated in           ${((Date.now() - started) / 1000).toFixed(1)}s (seed ${SEED})`);
  console.log('');
  console.log('  NOTE: every distributor, price, scheme and stock figure above is');
  console.log('  synthetic demo data generated locally. No external platform is involved.');
  console.log('');
}

if (require.main === module) {
  try {
    seedV2();
    closeDb();
  } catch (err) {
    console.error('\n  Procurement seeding failed:', err instanceof Error ? err.message : err);
    closeDb();
    process.exit(1);
  }
}
